In [2]:
import pandas as pd
import numpy as np

from sklearn.preprocessing import LabelEncoder
from sklearn.model_selection import train_test_split

from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Embedding, LSTM, Dense, Dropout, Bidirectional
from tensorflow.keras.preprocessing.text import Tokenizer
from tensorflow.keras.preprocessing.sequence import pad_sequences
from tensorflow.keras.callbacks import EarlyStopping

from googletrans import Translator

In [1]:
pip install googletrans==4.0.0-rc1

Collecting googletrans==4.0.0-rc1
  Downloading googletrans-4.0.0rc1.tar.gz (20 kB)
  Preparing metadata (setup.py) ... done
Collecting httpx==0.13.3 (from googletrans==4.0.0-rc1)
  Downloading httpx-0.13.3-py3-none-any.whl.metadata (25 kB)
Requirement already satisfied: certifi in /usr/local/lib/python3.12/dist-packages (from httpx==0.13.3->googletrans==4.0.0-rc1) (2026.4.22)
Collecting hstspreload (from httpx==0.13.3->googletrans==4.0.0-rc1)
  Downloading hstspreload-2025.1.1-py3-none-any.whl.metadata (2.1 kB)
Requirement already satisfied: sniffio in /usr/local/lib/python3.12/dist-packages (from httpx==0.13.3->googletrans==4.0.0-rc1) (1.3.1)
Collecting chardet==3.* (from httpx==0.13.3->googletrans==4.0.0-rc1)
  Downloading chardet-3.0.4-py2.py3-none-any.whl.metadata (3.2 kB)
Collecting idna==2.* (from httpx==0.13.3->googletrans==4.0.0-rc1)
  Downloading idna-2.10-py2.py3-none-any.whl.metadata (9.1 kB)
Collecting rfc3986<2,>=1.3 (from httpx==0.13.3->googletrans==4.0.0-rc1)
  Downloading rfc3986-1.5.0-py2.py3-none-any.whl.metadata (6.5 kB)
Collecting httpcore==0.9.* (from httpx==0.13.3->googletrans==4.0.0-rc1)
  Downloading httpcore-0.9.1-py3-none-any.whl.metadata (4.6 kB)
Collecting h11<0.10,>=0.8 (from httpcore==0.9.*->httpx==0.13.3->googletrans==4.0.0-rc1)
  Downloading h11-0.9.0-py2.py3-none-any.whl.metadata (8.1 kB)
Collecting h2==3.* (from httpcore==0.9.*->httpx==0.13.3->googletrans==4.0.0-rc1)
  Downloading h2-3.2.0-py2.py3-none-any.whl.metadata (32 kB)
Collecting hyperframe<6,>=5.2.0 (from h2==3.*->httpcore==0.9.*->httpx==0.13.3->googletrans==4.0.0-rc1)
  Downloading hyperframe-5.2.0-py2.py3-none-any.whl.metadata (7.2 kB)
Collecting hpack<4,>=3.0 (from h2==3.*->httpcore==0.9.*->httpx==0.13.3->googletrans==4.0.0-rc1)
  Downloading hpack-3.0.0-py2.py3-none-any.whl.metadata (7.0 kB)
Downloading httpx-0.13.3-py3-none-any.whl (55 kB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 55.1/55.1 kB 6.3 MB/s eta 0:00:00
Downloading chardet-3.0.4-py2.py3-none-any.whl (133 kB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 133.4/133.4 kB 10.8 MB/s eta 0:00:00
Downloading httpcore-0.9.1-py3-none-any.whl (42 kB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 42.6/42.6 kB 4.7 MB/s eta 0:00:00
Downloading idna-2.10-py2.py3-none-any.whl (58 kB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 58.8/58.8 kB 7.3 MB/s eta 0:00:00
Downloading h2-3.2.0-py2.py3-none-any.whl (65 kB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 65.0/65.0 kB 8.1 MB/s eta 0:00:00
Downloading rfc3986-1.5.0-py2.py3-none-any.whl (31 kB)
Downloading hstspreload-2025.1.1-py3-none-any.whl (1.3 MB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 1.3/1.3 MB 50.6 MB/s eta 0:00:00
Downloading h11-0.9.0-py2.py3-none-any.whl (53 kB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 53.6/53.6 kB 5.3 MB/s eta 0:00:00
Downloading hpack-3.0.0-py2.py3-none-any.whl (38 kB)
Downloading hyperframe-5.2.0-py2.py3-none-any.whl (12 kB)
Building wheels for collected packages: googletrans
  Building wheel for googletrans (setup.py) ... done
  Created wheel for googletrans: filename=googletrans-4.0.0rc1-py3-none-any.whl size=17396 sha256=5a10328bc46cd54792c56c631c268fbb2da4b1a876a364d5955a985bb0739def
  Stored in directory: /root/.cache/pip/wheels/95/0f/04/b17a72024b56a60e499ce1a6313d283ed5ba332407155bee03
Successfully built googletrans
Installing collected packages: rfc3986, hyperframe, hpack, h11, chardet, idna, hstspreload, h2, httpcore, httpx, googletrans
  Attempting uninstall: hyperframe
    Found existing installation: hyperframe 6.1.0
    Uninstalling hyperframe-6.1.0:
      Successfully uninstalled hyperframe-6.1.0
  Attempting uninstall: hpack
    Found existing installation: hpack 4.1.0
    Uninstalling hpack-4.1.0:
      Successfully uninstalled hpack-4.1.0
  Attempting uninstall: h11
    Found existing installation: h11 0.16.0
    Uninstalling h11-0.16.0:
      Successfully uninstalled h11-0.16.0
  Attempting uninstall: chardet
    Found existing installation: chardet 5.2.0
    Uninstalling chardet-5.2.0:
      Successfully uninstalled chardet-5.2.0
  Attempting uninstall: idna
    Found existing installation: idna 3.13
    Uninstalling idna-3.13:
      Successfully uninstalled idna-3.13
  Attempting uninstall: h2
    Found existing installation: h2 4.3.0
    Uninstalling h2-4.3.0:
      Successfully uninstalled h2-4.3.0
  Attempting uninstall: httpcore
    Found existing installation: httpcore 1.0.9
    Uninstalling httpcore-1.0.9:
      Successfully uninstalled httpcore-1.0.9
  Attempting uninstall: httpx
    Found existing installation: httpx 0.28.1
    Uninstalling httpx-0.28.1:
      Successfully uninstalled httpx-0.28.1
ERROR: pip's dependency resolver does not currently take into account all the packages that are installed. This behaviour is the source of the following dependency conflicts.
mcp 1.27.0 requires httpx>=0.27.1, but you have httpx 0.13.3 which is incompatible.
gradio 5.50.0 requires httpx<1.0,>=0.24.1, but you have httpx 0.13.3 which is incompatible.
firebase-admin 6.9.0 requires httpx[http2]==0.28.1, but you have httpx 0.13.3 which is incompatible.
gradio-client 1.14.0 requires httpx>=0.24.1, but you have httpx 0.13.3 which is incompatible.
google-genai 1.68.0 requires httpx<1.0.0,>=0.28.1, but you have httpx 0.13.3 which is incompatible.
langgraph-sdk 0.3.13 requires httpx>=0.25.2, but you have httpx 0.13.3 which is incompatible.
huggingface-hub 1.11.0 requires httpx<1,>=0.23.0, but you have httpx 0.13.3 which is incompatible.
weasel 1.0.0 requires httpx>=0.24.0, but you have httpx 0.13.3 which is incompatible.
google-adk 1.29.0 requires httpx<1.0.0,>=0.27.0, but you have httpx 0.13.3 which is incompatible.
openai 2.32.0 requires httpx<1,>=0.23.0, but you have httpx 0.13.3 which is incompatible.
langsmith 0.7.34 requires httpx<1,>=0.23.0, but you have httpx 0.13.3 which is incompatible.
Successfully installed chardet-3.0.4 googletrans-4.0.0rc1 h11-0.9.0 h2-3.2.0 hpack-3.0.0 hstspreload-2025.1.1 httpcore-0.9.1 httpx-0.13.3 hyperframe-5.2.0 idna-2.10 rfc3986-1.5.0

In [6]:
data =pd.read_csv("Language Detection.csv")
data

                                                    Text Language
0       Nature, in the broadest sense, is the natural...  English
1      "Nature" can refer to the phenomena of the phy...  English
2      The study of nature is a large, if not the onl...  English
3      Although humans are part of nature, human acti...  English
4      [1] The word nature is borrowed from the Old F...  English
...                                                  ...      ...
10332  ನಿಮ್ಮ ತಪ್ಪು ಏನು ಬಂದಿದೆಯೆಂದರೆ ಆ ದಿನದಿಂದ ನಿಮಗೆ ಒ...  Kannada
10333  ನಾರ್ಸಿಸಾ ತಾನು ಮೊದಲಿಗೆ ಹೆಣಗಾಡುತ್ತಿದ್ದ ಮಾರ್ಗಗಳನ್...  Kannada
10334  ಹೇಗೆ ' ನಾರ್ಸಿಸಿಸಮ್ ಈಗ ಮರಿಯನ್ ಅವರಿಗೆ ಸಂಭವಿಸಿದ ಎ...  Kannada
10335  ಅವಳು ಈಗ ಹೆಚ್ಚು ಚಿನ್ನದ ಬ್ರೆಡ್ ಬಯಸುವುದಿಲ್ಲ ಎಂದು ...  Kannada
10336  ಟೆರ್ರಿ ನೀವು ನಿಜವಾಗಿಯೂ ಆ ದೇವದೂತನಂತೆ ಸ್ವಲ್ಪ ಕಾಣು...  Kannada

[10337 rows x 2 columns]

In [7]:
print(data.head())

                                                Text Language
0   Nature, in the broadest sense, is the natural...  English
1  "Nature" can refer to the phenomena of the phy...  English
2  The study of nature is a large, if not the onl...  English
3  Although humans are part of nature, human acti...  English
4  [1] The word nature is borrowed from the Old F...  English

In [8]:
data = data.dropna()

In [9]:
texts = data["Text"].astype(str)
texts

0         Nature, in the broadest sense, is the natural...
1        "Nature" can refer to the phenomena of the phy...
2        The study of nature is a large, if not the onl...
3        Although humans are part of nature, human acti...
4        [1] The word nature is borrowed from the Old F...
                               ...
10332    ನಿಮ್ಮ ತಪ್ಪು ಏನು ಬಂದಿದೆಯೆಂದರೆ ಆ ದಿನದಿಂದ ನಿಮಗೆ ಒ...
10333    ನಾರ್ಸಿಸಾ ತಾನು ಮೊದಲಿಗೆ ಹೆಣಗಾಡುತ್ತಿದ್ದ ಮಾರ್ಗಗಳನ್...
10334    ಹೇಗೆ ' ನಾರ್ಸಿಸಿಸಮ್ ಈಗ ಮರಿಯನ್ ಅವರಿಗೆ ಸಂಭವಿಸಿದ ಎ...
10335    ಅವಳು ಈಗ ಹೆಚ್ಚು ಚಿನ್ನದ ಬ್ರೆಡ್ ಬಯಸುವುದಿಲ್ಲ ಎಂದು ...
10336    ಟೆರ್ರಿ ನೀವು ನಿಜವಾಗಿಯೂ ಆ ದೇವದೂತನಂತೆ ಸ್ವಲ್ಪ ಕಾಣು...
Name: Text, Length: 10337, dtype: object

In [11]:
languages = data["Language"]
languages

0        English
1        English
2        English
3        English
4        English
          ...
10332    Kannada
10333    Kannada
10334    Kannada
10335    Kannada
10336    Kannada
Name: Language, Length: 10337, dtype: object

In [13]:
encoder = LabelEncoder()
labels = encoder.fit_transform(languages)
labels

array([3, 3, 3, ..., 9, 9, 9])

In [14]:
tokenizer = Tokenizer(
    char_level=True,
    lower=True,
    oov_token="<OOV>"
)

tokenizer.fit_on_texts(texts)

In [15]:
sequences = tokenizer.texts_to_sequences(texts)
sequences

[[2,
  6,
  4,
  8,
  13,
  9,
  3,
  19,
  2,
  5,
  6,
  2,
  8,
  18,
  3,
  2,
  24,
  9,
  7,
  4,
  11,
  3,
  10,
  8,
  2,
  10,
  3,
  6,
  10,
  3,
  19,
  2,
  5,
  10,
  2,
  8,
  18,
  3,
  2,
  6,
  4,
  8,
  13,
  9,
  4,
  12,
  19,
  2,
  16,
  18,
  29,
  10,
  5,
  14,
  4,
  12,
  19,
  2,
  15,
  4,
  8,
  3,
  9,
  5,
  4,
  12,
  2,
  28,
  7,
  9,
  12,
  11,
  2,
  7,
  9,
  2,
  13,
  6,
  5,
  20,
  3,
  9,
  10,
  3,
  21],
 [138,
  6,
  4,
  8,
  13,
  9,
  3,
  138,
  2,
  14,
  4,
  6,
  2,
  9,
  3,
  23,
  3,
  9,
  2,
  8,
  7,
  2,
  8,
  18,
  3,
  2,
  16,
  18,
  3,
  6,
  7,
  15,
  3,
  6,
  4,
  2,
  7,
  23,
  2,
  8,
  18,
  3,
  2,
  16,
  18,
  29,
  10,
  5,
  14,
  4,
  12,
  2,
  28,
  7,
  9,
  12,
  11,
  19,
  2,
  4,
  6,
  11,
  2,
  4,
  12,
  10,
  7,
  2,
  8,
  7,
  2,
  12,
  5,
  23,
  3,
  2,
  5,
  6,
  2,
  17,
  3,
  6,
  3,
  9,
  4,
  12,
  21],
 [8,
  18,
  3,
  2,
  10,
  8,
  13,
  11,
  29,
  2,
  7,
  23,
  2,
  6,
  4,
  8,
  13,
  9,
  3,
  2,
  5,
  10,
  2,
  4,
  2,
  12,
  4,
  9,
  17,
  3,
  19,
  2,
  5,
  23,
  2,
  6,
  7,
  8,
  2,
  8,
  18,
  3,
  2,
  7,
  6,
  12,
  29,
  19,
  2,
  16,
  4,
  9,
  8,
  2,
  7,
  23,
  2,
  10,
  14,
  5,
  3,
  6,
  14,
  3,
  21],
 [4,
  12,
  8,
  18,
  7,
  13,
  17,
  18,
  2,
  18,
  13,
  15,
  4,
  6,
  10,
  2,
  4,
  9,
  3,
  2,
  16,
  4,
  9,
  8,
  2,
  7,
  23,
  2,
  6,
  4,
  8,
  13,
  9,
  3,
  19,
  2,
  18,
  13,
  15,
  4,
  6,
  2,
  4,
  14,
  8,
  5,
  20,
  5,
  8,
  29,
  2,
  5,
  10,
  2,
  7,
  23,
  8,
  3,
  6,
  2,
  13,
  6,
  11,
  3,
  9,
  10,
  8,
  7,
  7,
  11,
  2,
  4,
  10,
  2,
  4,
  2,
  10,
  3,
  16,
  4,
  9,
  4,
  8,
  3,
  2,
  14,
  4,
  8,
  3,
  17,
  7,
  9,
  29,
  2,
  23,
  9,
  7,
  15,
  2,
  7,
  8,
  18,
  3,
  9,
  2,
  6,
  4,
  8,
  13,
  9,
  4,
  12,
  2,
  16,
  18,
  3,
  6,
  7,
  15,
  3,
  6,
  4,
  21],
 [68,
  76,
  69,
  2,
  8,
  18,
  3,
  2,
  28,
  7,
  9,
  11,
  2,
  6,
  4,
  8,
  13,
  9,
  3,
  2,
  5,
  10,
  2,
  24,
  7,
  9,
  9,
  7,
  28,
  3,
  11,
  2,
  23,
  9,
  7,
  15,
  2,
  8,
  18,
  3,
  2,
  7,
  12,
  11,
  2,
  23,
  9,
  3,
  6,
  14,
  18,
  2,
  6,
  4,
  8,
  13,
  9,
  3,
  2,
  4,
  6,
  11,
  2,
  5,
  10,
  2,
  11,
  3,
  9,
  5,
  20,
  3,
  11,
  2,
  23,
  9,
  7,
  15,
  2,
  8,
  18,
  3,
  2,
  12,
  4,
  8,
  5,
  6,
  2,
  28,
  7,
  9,
  11,
  2,
  6,
  4,
  8,
  13,
  9,
  4,
  19,
  2,
  7,
  9,
  2,
  138,
  3,
  10,
  10,
  3,
  6,
  8,
  5,
  4,
  12,
  2,
  43,
  13,
  4,
  12,
  5,
  8,
  5,
  3,
  10,
  19,
  2,
  5,
  6,
  6,
  4,
  8,
  3,
  2,
  11,
  5,
  10,
  16,
  7,
  10,
  5,
  8,
  5,
  7,
  6,
  138,
  19,
  2,
  4,
  6,
  11,
  2,
  5,
  6,
  2,
  4,
  6,
  14,
  5,
  3,
  6,
  8,
  2,
  8,
  5,
  15,
  3,
  10,
  19,
  2,
  12,
  5,
  8,
  3,
  9,
  4,
  12,
  12,
  29,
  2,
  15,
  3,
  4,
  6,
  8,
  2,
  138,
  24,
  5,
  9,
  8,
  18,
  138,
  21],
 [68,
  66,
  69,
  2,
  5,
  6,
  2,
  4,
  6,
  14,
  5,
  3,
  6,
  8,
  2,
  16,
  18,
  5,
  12,
  7,
  10,
  7,
  16,
  18,
  29,
  19,
  2,
  6,
  4,
  8,
  13,
  9,
  4,
  2,
  5,
  10,
  2,
  15,
  7,
  10,
  8,
  12,
  29,
  2,
  13,
  10,
  3,
  11,
  2,
  4,
  10,
  2,
  8,
  18,
  3,
  2,
  12,
  4,
  8,
  5,
  6,
  2,
  8,
  9,
  4,
  6,
  10,
  12,
  4,
  8,
  5,
  7,
  6,
  2,
  7,
  23,
  2,
  8,
  18,
  3,
  2,
  17,
  9,
  3,
  3,
  22,
  2,
  28,
  7,
  9,
  11,
  2,
  16,
  18,
  29,
  10,
  5,
  10,
  2,
  148,
  282,
  279,
  114,
  77,
  171,
  149,
  19,
  2,
  28,
  18,
  5,
  14,
  18,
  2,
  7,
  9,
  5,
  17,
  5,
  6,
  4,
  12,
  12,
  29,
  2,
  9,
  3,
  12,
  4,
  8,
  3,
  11,
  2,
  8,
  7,
  2,
  8,
  18,
  3,
  2,
  5,
  6,
  8,
  9,
  5,
  6,
  10,
  5,
  14,
  2,
  14,
  18,
  4,
  9,
  4,
  14,
  8,
  3,
  9,
  5,
  10,
  8,
  5,
  14,
  10,
  2,
  8,
  18,
  4,
  8,
  2,
  16,
  12,
  4,
  6,
  8,
  10,
  19,
  2,
  4,
  6,
  5,
  15,
  4,
  12,
  10,
  19,
  2,
  4,
  6,
  11,
  2,
  7,
  8,
  18,
  3,
  9,
  2,
  23,
  3,
  4,
  8,
  13,
  9,
  3,
  10,
  2,
  7,
  23,
  2,
  8,
  18,
  3,
  2,
  28,
  7,
  9,
  12,
  11,
  2,
  11,
  3,
  20,
  3,
  12,
  7,
  16,
  2,
  7,
  23,
  2,
  8,
  18,
  3,
  5,
  9,
  2,
  7,
  28,
  6,
  2,
  4,
  14,
  14,
  7,
  9,
  11,
  21],
 [68,
  157,
  69,
  68,
  189,
  69,
  2,
  234,
  8,
  18,
  3,
  2,
  14,
  7,
  6,
  14,
  3,
  16,
  8,
  2,
  7,
  23,
  2,
  6,
  4,
  8,
  13,
  9,
  3,
  2,
  4,
  10,
  2,
  4,
  2,
  28,
  18,
  7,
  12,
  3,
  19,
  2,
  8,
  18,
  3,
  2,
  16,
  18,
  29,
  10,
  5,
  14,
  4,
  12,
  2,
  13,
  6,
  5,
  20,
  3,
  9,
  10,
  3,
  19,
  2,
  5,
  10,
  2,
  7,
  6,
  3,
  2,
  7,
  23,
  2,
  10,
  3,
  20,
  3,
  9,
  4,
  12,
  2,
  3,
  111,
  16,
  4,
  6,
  10,
  5,
  7,
  6,
  10,
  2,
  7,
  23,
  2,
  8,
  18,
  3,
  2,
  7,
  9,
  5,
  17,
  5,
  6,
  4,
  12,
  2,
  6,
  7,
  8,
  5,
  7,
  6,
  304,
  68,
  76,
  69,
  2,
  5,
  8,
  2,
  24,
  3,
  17,
  4,
  6,
  2,
  28,
  5,
  8,
  18,
  2,
  14,
  3,
  9,
  8,
  4,
  5,
  6,
  2,
  14,
  7,
  9,
  3,
  2,
  4,
  16,
  16,
  12,
  5,
  14,
  4,
  8,
  5,
  7,
  6,
  10,
  2,
  7,
  23,
  2,
  8,
  18,
  3,
  2,
  28,
  7,
  9,
  11,
  2,
  282,
  279,
  114,
  77,
  171,
  2,
  24,
  29,
  2,
  16,
  9,
  3,
  139,
  10,
  7,
  14,
  9,
  4,
  8,
  5,
  14,
  2,
  16,
  18,
  5,
  12,
  7,
  10,
  7,
  16,
  18,
  3,
  9,
  10,
  2,
  148,
  8,
  18,
  7,
  13,
  17,
  18,
  2,
  8,
  18,
  5,
  10,
  2,
  28,
  7,
  9,
  11,
  2,
  18,
  4,
  11,
  2,
  4,
  2,
  11,
  29,
  6,
  4,
  15,
  5,
  14,
  2,
  11,
  5,
  15,
  3,
  6,
  10,
  5,
  7,
  6,
  2,
  8,
  18,
  3,
  6,
  19,
  2,
  3,
  10,
  16,
  3,
  14,
  5,
  4,
  12,
  12,
  29,
  2,
  23,
  7,
  9,
  2,
  18,
  3,
  9,
  4,
  14,
  12,
  5,
  8,
  13,
  10,
  149,
  19,
  2,
  4,
  6,
  11,
  2,
  18,
  4,
  10,
  2,
  10,
  8,
  3,
  4,
  11,
  5,
  12,
  29,
  2,
  17,
  4,
  5,
  6,
  3,
  11,
  2,
  14,
  13,
  9,
  9,
  3,
  6,
  14,
  29,
  2,
  3,
  20,
  3,
  9,
  2,
  10,
  5,
  6,
  14,
  3,
  21],
 [11,
  13,
  9,
  5,
  6,
  17,
  2,
  8,
  18,
  3,
  2,
  4,
  11,
  20,
  3,
  6,
  8,
  2,
  7,
  23,
  2,
  15,
  7,
  11,
  3,
  9,
  6,
  2,
  10,
  14,
  5,
  3,
  6,
  8,
  5,
  23,
  5,
  14,
  2,
  15,
  3,
  8,
  18,
  7,
  11,
  2,
  5,
  6,
  2,
  8,
  18,
  3,
  2,
  12,
  4,
  10,
  8,
  2,
  10,
  3,
  20,
  3,
  9,
  4,
  12,
  2,
  14,
  3,
  6,
  8,
  13,
  9,
  5,
  3,
  10,
  19,
  2,
  6,
  4,
  8,
  13,
  9,
  3,
  2,
  24,
  3,
  14,
  4,
  15,
  3,
  2,
  8,
  18,
  3,
  2,
  16,
  4,
  10,
  10,
  5,
  20,
  3,
  2,
  9,
  3,
  4,
  12,
  5,
  8,
  29,
  19,
  2,
  7,
  9,
  17,
  4,
  6,
  5,
  47,
  3,
  11,
  2,
  4,
  6,
  11,
  2,
  15,
  7,
  20,
  3,
  11,
  2,
  24,
  29,
  2,
  11,
  5,
  20,
  5,
  6,
  3,
  2,
  12,
  4,
  28,
  10,
  21],
 [68,
  172,
  69,
  68,
  193,
  69,
  2,
  28,
  5,
  8,
  18,
  2,
  8,
  18,
  3,
  2,
  5,
  6,
  11,
  13,
  10,
  8,
  9,
  5,
  4,
  12,
  2,
  9,
  3,
  20,
  7,
  12,
  13,
  8,
  5,
  7,
  6,
  19,
  2,
  6,
  4,
  8,
  13,
  9,
  3,
  2,
  5,
  6,
  14,
  9,
  3,
  4,
  10,
  5,
  6,
  17,
  12,
  29,
  2,
  24,
  3,
  14,
  4,
  15,
  3,
  2,
  10,
  3,
  3,
  6,
  2,
  4,
  10,
  2,
  8,
  18,
  3,
  2,
  16,
  4,
  9,
  8,
  2,
  7,
  23,
  2,
  9,
  3,
  4,
  12,
  5,
  8,
  29,
  2,
  11,
  3,
  16,
  9,
  5,
  20,
  3,
  11,
  2,
  23,
  9,
  7,
  15,
  2,
  5,
  6,
  8,
  3,
  6,
  8,
  5,
  7,
  6,
  4,
  12,
  2,
  5,
  6,
  8,
  3,
  9,
  20,
  3,
  6,
  8,
  5,
  7,
  6,
  154,
  226,
  2,
  5,
  8,
  2,
  28,
  4,
  10,
  2,
  18,
  3,
  6,
  14,
  3,
  2,
  14,
  7,
  6,
  10,
  5,
  11,
  3,
  9,
  3,
  11,
  2,
  4,
  10,
  2,
  10,
  4,
  14,
  9,
  3,
  11,
  2,
  24,
  29,
  2,
  10,
  7,
  15,
  3,
  2,
  8,
  9,
  4,
  11,
  5,
  8,
  5,
  7,
  6,
  10,
  2,
  148,
  9,
  7,
  13,
  10,
  10,
  3,
  4,
  13,
  19,
  2,
  4,
  15,
  3,
  9,
  5,
  14,
  4,
  6,
  2,
  8,
  9,
  4,
  6,
  10,
  14,
  3,
  6,
  11,
  3,
  6,
  8,
  4,
  12,
  5,
  10,
  15,
  149,
  2,
  7,
  9,
  2,
  4,
  2,
  15,
  3,
  9,
  3,
  2,
  11,
  3,
  14,
  7,
  9,
  13,
  15,
  2,
  23,
  7,
  9,
  2,
  11,
  5,
  20,
  5,
  6,
  3,
  2,
  16,
  9,
  7,
  20,
  5,
  11,
  3,
  6,
  14,
  3,
  2,
  7,
  9,
  2,
  18,
  13,
  15,
  4,
  6,
  2,
  18,
  5,
  10,
  8,
  7,
  9,
  29,
  2,
  148,
  18,
  3,
  17,
  3,
  12,
  19,
  2,
  15,
  4,
  9,
  111,
  149,
  21],
 [18,
  7,
  28,
  3,
  20,
  3,
  9,
  19,
  2,
  4,
  2,
  20,
  5,
  8,
  4,
  12,
  5,
  10,
  8,
  2,
  20,
  5,
  10,
  5,
  7,
  6,
  2,
  7,
  23,
  2,
  6,
  4,
  8,
  13,
  9,
  3,
  19,
  2,
  14,
  12,
  7,
  10,
  3,
  9,
  2,
  8,
  7,
  2,
  8,
  18,
  3,
  2,
  16,
  9,
  3,
  10,
  7,
  14,
  9,
  4,
  8,
  5,
  14,
  2,
  7,
  6,
  3,
  19,
  2,
  17,
  7,
  8,
  2,
  9,
  3,
  24,
  7,
  9,
  6,
  2,
  4,
  8,
  2,
  8,
  18,
  3,
  2,
  10,
  4,
  15,
  3,
  2,
  8,
  5,
  15,
  3,
  19,
  2,
  3,
  10,
  16,
  3,
  14,
  5,
  4,
  12,
  12,
  29,
  2,
  4,
  23,
  8,
  3,
  9,
  2,
  14,
  18,
  4,
  9,
  12,
  3,
  10,
  2,
  11,
  4,
  9,
  28,
  5,
  6,
  21],
 [68,
  76,
  69,
  2,
  28,
  5,
  8,
  18,
  5,
  6,
  2,
  8,
  18,
  3,
  2,
  20,
  4,
  9,
  5,
  7,
  13,
  10,
  2,
  13,
  10,
  3,
  10,
  2,
  7,
  23,
  2,
  8,
  18,
  3,
  2,
  28,
  7,
  9,
  11,
  2,
  8,
  7,
  11,
  4,
  29,
  19,
  2,
  138,
  6,
  4,
  8,
  13,
  9,
  3,
  138,
  2,
  7,
  23,
  8,
  3,
  6,
  2,
  9,
  3,
  23,
  3,
  9,
  10,
  2,
  8,
  7,
  2,
  17,
  3,
  7,
  12,
  7,
  17,
  29,
  2,
  4,
  6,
  11,
  2,
  28,
  5,
  12,
  11,
  12,
  5,
  23,
  3,
  21],
 [6,
  4,
  8,
  13,
  9,
  3,
  2,
  14,
  4,
  6,
  2,
  9,
  3,
  23,
  3,
  9,
  2,
  8,
  7,
  2,
  8,
  18,
  3,
  2,
  17,
  3,
  6,
  3,
  9,
  4,
  12,
  2,
  9,
  3,
  4,
  12,
  15,
  2,
  7,
  23,
  2,
  12,
  5,
  20,
  5,
  6,
  17,
  2,
  16,
  12,
  4,
  6,
  8,
  10,
  2,
  4,
  6,
  11,
  2,
  4,
  6,
  5,
  15,
  4,
  12,
  10,
  19,
  2,
  4,
  6,
  11,
  2,
  5,
  6,
  2,
  10,
  7,
  15,
  3,
  2,
  14,
  4,
  10,
  3,
  10,
  2,
  8,
  7,
  2,
  8,
  18,
  3,
  2,
  16,
  9,
  7,
  14,
  3,
  10,
  10,
  3,
  10,
  2,
  4,
  10,
  10,
  7,
  14,
  5,
  4,
  8,
  3,
  11,
  2,
  28,
  5,
  8,
  18,
  2,
  5,
  6,
  4,
  6,
  5,
  15,
  4,
  8,
  3,
  2,
  7,
  24,
  52,
  3,
  14,
  8,
  10,
  310,
  8,
  18,
  3,
  2,
  28,
  4,
  29,
  2,
  8,
  18,
  4,
  8,
  2,
  16,
  4,
  9,
  8,
  5,
  14,
  13,
  12,
  4,
  9,
  2,
  8,
  29,
  16,
  3,
  10,
  2,
  7,
  23,
  2,
  8,
  18,
  5,
  6,
  17,
  10,
  2,
  3,
  111,
  5,
  10,
  8,
  2,
  4,
  6,
  11,
  2,
  14,
  18,
  4,
  6,
  17,
  3,
  2,
  7,
  23,
  2,
  8,
  18,
  3,
  5,
  9,
  2,
  7,
  28,
  6,
  2,
  4,
  14,
  14,
  7,
  9,
  11,
  19,
  2,
  10,
  13,
  14,
  18,
  2,
  4,
  10,
  2,
  8,
  18,
  3,
  2,
  28,
  3,
  4,
  8,
  18,
  3,
  9,
  2,
  4,
  6,
  11,
  2,
  17,
  3,
  7,
  12,
  7,
  17,
  29,
  2,
  7,
  23,
  2,
  8,
  18,
  3,
  2,
  3,
  4,
  9,
  8,
  18,
  21],
 [5,
  8,
  2,
  5,
  10,
  2,
  7,
  23,
  8,
  3,
  6,
  2,
  8,
  4,
  22,
  3,
  6,
  2,
  8,
  7,
  2,
  15,
  3,
  4,
  6,
  2,
  8,
  18,
  3,
  2,
  138,
  6,
  4,
  8,
  13,
  9,
  4,
  12,
  2,
  3,
  6,
  20,
  5,
  9,
  7,
  6,
  15,
  3,
  6,
  8,
  138,
  2,
  7,
  9,
  2,
  28,
  5,
  12,
  11,
  3,
  9,
  6,
  3,
  10,
  10,
  310,
  28,
  5,
  12,
  11,
  2,
  4,
  6,
  5,
  15,
  4,
  12,
  10,
  19,
  2,
  9,
  7,
  14,
  22,
  10,
  19,
  2,
  23,
  7,
  9,
  3,
  10,
  8,
  19,
  2,
  4,
  6,
  11,
  2,
  5,
  6,
  2,
  17,
  3,
  6,
  3,
  9,
  4,
  12,
  2,
  8,
  18,
  7,
  10,
  3,
  2,
  8,
  18,
  5,
  6,
  17,
  10,
  2,
  8,
  18,
  4,
  8,
  2,
  18,
  4,
  20,
  3,
  2,
  6,
  7,
  8,
  2,
  24,
  3,
  3,
  6,
  2,
  10,
  13,
  24,
  10,
  8,
  4,
  6,
  8,
  5,
  4,
  12,
  12,
  29,
  2,
  4,
  12,
  8,
  3,
  9,
  3,
  11,
  2,
  24,
  29,
  2,
  18,
  13,
  15,
  4,
  6,
  2,
  5,
  6,
  8,
  3,
  9,
  20,
  3,
  6,
  8,
  5,
  7,
  6,
  19,
  2,
  7,
  9,
  2,
  28,
  18,
  5,
  14,
  18,
  2,
  16,
  3,
  9,
  10,
  5,
  10,
  8,
  2,
  11,
  3,
  10,
  16,
  5,
  8,
  3,
  2,
  18,
  13,
  15,
  4,
  6,
  2,
  5,
  6,
  8,
  3,
  9,
  20,
  3,
  6,
  8,
  5,
  7,
  6,
  21],
 [23,
  7,
  9,
  2,
  3,
  111,
  4,
  15,
  16,
  12,
  3,
  19,
  2,
  15,
  4,
  6,
  13,
  23,
  4,
  14,
  8,
  13,
  9,
  3,
  11,
  2,
  7,
  24,
  52,
  3,
  14,
  8,
  10,
  2,
  4,
  6,
  11,
  2,
  18,
  13,
  15,
  4,
  6,
  2,
  5,
  6,
  8,
  3,
  9,
  4,
  14,
  8,
  5,
  7,
  6,
  2,
  17,
  3,
  6,
  3,
  9,
  4,
  12,
  12,
  29,
  2,
  4,
  9,
  3,
  2,
  6,
  7,
  8,
  2,
  14,
  7,
  6,
  10,
  5,
  11,
  3,
  9,
  3,
  11,
  2,
  16,
  4,
  9,
  8,
  2,
  7,
  23,
  2,
  6,
  4,
  8,
  13,
  9,
  3,
  19,
  2,
  13,
  6,
  12,
  3,
  10,
  10,
  2,
  43,
  13,
  4,
  12,
  5,
  23,
  5,
  3,
  11,
  2,
  4,
  10,
  19,
  2,
  23,
  7,
  9,
  2,
  3,
  111,
  4,
  15,
  16,
  12,
  3,
  19,
  2,
  138,
  18,
  13,
  15,
  4,
  6,
  2,
  6,
  4,
  8,
  13,
  9,
  3,
  138,
  2,
  7,
  9,
  2,
  138,
  8,
  18,
  3,
  2,
  28,
  18,
  7,
  12,
  3,
  2,
  7,
  23,
  2,
  6,
  4,
  8,
  13,
  9,
  3,
  138,
  21],
 [8,
  18,
  5,
  10,
  2,
  15,
  7,
  9,
  3,
  2,
  8,
  9,
  4,
  11,
  5,
  8,
  5,
  7,
  6,
  4,
  12,
  2,
  14,
  7,
  6,
  14,
  3,
  16,
  8,
  2,
  7,
  23,
  2,
  6,
  4,
  8,
  13,
  9,
  4,
  12,
  2,
  8,
  18,
  5,
  6,
  17,
  10,
  2,
  8,
  18,
  4,
  8,
  2,
  14,
  4,
  6,
  2,
  10,
  8,
  5,
  12,
  12,
  2,
  24,
  3,
  2,
  23,
  7,
  13,
  6,
  11,
  2,
  8,
  7,
  11,
  4,
  29,
  2,
  5,
  15,
  16,
  12,
  5,
  3,
  10,
  2,
  4,
  2,
  11,
  5,
  10,
  8,
  5,
  6,
  14,
  8,
  5,
  7,
  6,
  2,
  24,
  3,
  8,
  28,
  3,
  3,
  6,
  2,
  8,
  18,
  3,
  2,
  6,
  4,
  8,
  13,
  9,
  4,
  12,
  2,
  4,
  6,
  11,
  2,
  8,
  18,
  3,
  2,
  4,
  9,
  8,
  5,
  23,
  5,
  14,
  5,
  4,
  12,
  19,
  2,
  28,
  5,
  8,
  18,
  2,
  8,
  18,
  3,
  2,
  4,
  9,
  8,
  5,
  23,
  5,
  14,
  5,
  4,
  12,
  2,
  24,
  3,
  5,
  6,
  17,
  2,
  13,
  6,
  11,
  3,
  9,
  10,
  8,
  7,
  7,
  11,
  2,
  4,
  10,
  2,
  8,
  18,
  4,
  8,
  2,
  28,
  18,
  5,
  14,
  18,
  2,
  18,
  4,
  10,
  2,
  24,
  3,
  3,
  6,
  2,
  24,
  9,
  7,
  13,
  17,
  18,
  8,
  2,
  5,
  6,
  8,
  7,
  2,
  24,
  3,
  5,
  6,
  17,
  2,
  24,
  29,
  2,
  4,
  2,
  18,
  13,
  15,
  4,
  6,
  2,
  14,
  7,
  6,
  10,
  14,
  5,
  7,
  13,
  10,
  6,
  3,
  10,
  10,
  2,
  7,
  9,
  2,
  4,
  2,
  18,
  13,
  15,
  4,
  6,
  2,
  15,
  5,
  6,
  11,
  21],
 [11,
  3,
  16,
  3,
  6,
  11,
  5,
  6,
  17,
  2,
  7,
  6,
  2,
  8,
  18,
  3,
  2,
  16,
  4,
  9,
  8,
  5,
  14,
  13,
  12,
  4,
  9,
  2,
  14,
  7,
  6,
  8,
  3,
  111,
  8,
  19,
  2,
  8,
  18,
  3,
  2,
  8,
  3,
  9,
  15,
  2,
  138,
  6,
  4,
  8,
  13,
  9,
  4,
  12,
  138,
  2,
  15,
  5,
  17,
  18,
  8,
  2,
  4,
  12,
  10,
  7,
  2,
  24,
  3,
  2,
  11,
  5,
  10,
  8,
  5,
  6,
  17,
  13,
  5,
  10,
  18,
  3,
  11,
  2,
  23,
  9,
  7,
  15,
  2,
  8,
  18,
  3,
  2,
  13,
  6,
  6,
  4,
  8,
  13,
  9,
  4,
  12,
  2,
  7,
  9,
  2,
  8,
  18,
  3,
  2,
  10,
  13,
  16,
  3,
  9,
  6,
  4,
  8,
  13,
  9,
  4,
  12,
  21],
 [68,
  76,
  69,
  2,
  3,
  4,
  9,
  8,
  18,
  2,
  5,
  10,
  2,
  8,
  18,
  3,
  2,
  7,
  6,
  12,
  29,
  2,
  16,
  12,
  4,
  6,
  3,
  8,
  2,
  22,
  6,
  7,
  28,
  6,
  2,
  8,
  7,
  2,
  10,
  13,
  16,
  16,
  7,
  9,
  8,
  2,
  12,
  5,
  23,
  3,
  19,
  2,
  4,
  6,
  11,
  2,
  5,
  8,
  10,
  2,
  6,
  4,
  8,
  13,
  9,
  4,
  12,
  2,
  23,
  3,
  4,
  8,
  13,
  9,
  3,
  10,
  2,
  4,
  9,
  3,
  2,
  8,
  18,
  3,
  2,
  10,
  13,
  24,
  52,
  3,
  14,
  8,
  2,
  7,
  23,
  2,
  15,
  4,
  6,
  29,
  2,
  23,
  5,
  3,
  12,
  11,
  10,
  2,
  7,
  23,
  2,
  10,
  14,
  5,
  3,
  6,
  8,
  5,
  23,
  5,
  14,
  2,
  9,
  3,
  10,
  3,
  4,
  9,
  14,
  18,
  21],
 [28,
  5,
  8,
  18,
  5,
  6,
  2,
  8,
  18,
  3,
  2,
  10,
  7,
  12,
  4,
  9,
  2,
  10,
  29,
  10,
  8,
  3,
  15,
  19,
  2,
  5,
  8,
  2,
  5,
  10,
  2,
  8,
  18,
  5,
  9,
  11,
  2,
  14,
  12,
  7,
  10,
  3,
  10,
  8,
  2,
  8,
  7,
  2,
  8,
  18,
  3,
  2,
  10,
  13,
  6,
  304,
  2,
  5,
  8,
  2,
  5,
  10,
  2,
  8,
  18,
  3,
  2,
  12,
  4,
  9,
  17,
  3,
  10,
  8,
  2,
  8,
  3,
  9,
  9,
  3,
  10,
  8,
  9,
  5,
  4,
  12,
  2,
  16,
  12,
  4,
  6,
  3,
  8,
  2,
  4,
  6,
  11,
  2,
  8,
  18,
  3,
  2,
  23,
  5,
  23,
  8,
  18,
  2,
  12,
  4,
  9,
  17,
  3,
  10,
  8,
  2,
  7,
  20,
  3,
  9,
  4,
  12,
  12,
  21],
 [5,
  8,
  10,
  2,
  15,
  7,
  10,
  8,
  2,
  16,
  9,
  7,
  15,
  5,
  6,
  3,
  6,
  8,
  2,
  14,
  12,
  5,
  15,
  4,
  8,
  5,
  14,
  2,
  23,
  3,
  4,
  8,
  13,
  9,
  3,
  10,
  2,
  4,
  9,
  3,
  2,
  5,
  8,
  10,
  2,
  8,
  28,
  7,
  2,
  12,
  4,
  9,
  17,
  3,
  2,
  16,
  7,
  12,
  4,
  9,
  2,
  9,
  3,
  17,
  5,
  7,
  6,
  10,
  19,
  2,
  8,
  28,
  7,
  2,
  9,
  3,
  12,
  4,
  8,
  5,
  20,
  3,
  12,
  29,
  2,
  6,
  4,
  9,
  9,
  7,
  28,
  2,
  8,
  3,
  15,
  16,
  3,
  9,
  4,
  8,
  3,
  2,
  47,
  7,
  6,
  3,
  10,
  19,
  2,
  4,
  6,
  11,
  2,
  4,
  2,
  28,
  5,
  11,
  3,
  2,
  3,
  43,
  13,
  4,
  8,
  7,
  9,
  5,
  4,
  12,
  2,
  8,
  9,
  7,
  16,
  5,
  14,
  4,
  12,
  2,
  8,
  7,
  2,
  10,
  13,
  24,
  8,
  9,
  7,
  16,
  5,
  14,
  4,
  12,
  2,
  9,
  3,
  17,
  5,
  7,
  6,
  21],
 [68,
  202,
  69,
  2,
  16,
  9,
  3,
  14,
  5,
  16,
  5,
  8,
  4,
  8,
  5,
  7,
  6,
  2,
  20,
  4,
  9,
  5,
  3,
  10,
  2,
  28,
  5,
  11,
  3,
  12,
  29,
  2,
  28,
  5,
  8,
  18,
  2,
  12,
  7,
  14,
  4,
  8,
  5,
  7,
  6,
  19,
  2,
  23,
  9,
  7,
  15,
  2,
  10,
  3,
  20,
  3,
  9,
  4,
  12,
  2,
  15,
  3,
  8,
  9,
  3,
  10,
  2,
  7,
  23,
  2,
  28,
  4,
  8,
  3,
  9,
  2,
  16,
  3,
  9,
  2,
  29,
  3,
  4,
  9,
  2,
  8,
  7,
  2,
  12,
  3,
  10,
  10,
  2,
  8,
  18,
  4,
  6,
  2,
  4,
  2,
  15,
  5,
  12,
  12,
  5,
  15,
  3,
  8,
  9,
  3,
  21],
 [202,
  76,
  2,
  16,
  3,
  9,
  14,
  3,
  6,
  8,
  2,
  7,
  23,
  2,
  8,
  18,
  3,
  2,
  3,
  4,
  9,
  8,
  18,
  72,
  10,
  2,
  10,
  13,
  9,
  23,
  4,
  14,
  3,
  2,
  5,
  10,
  2,
  14,
  7,
  20,
  3,
  9,
  3,
  11,
  2,
  24,
  29,
  2,
  10,
  4,
  12,
  8,
  139,
  28,
  4,
  8,
  3,
  9,
  2,
  7,
  14,
  3,
  4,
  6,
  10,
  21],
 [8,
  18,
  3,
  2,
  9,
  3,
  15,
  4,
  5,
  6,
  11,
  3,
  9,
  2,
  14,
  7,
  6,
  10,
  5,
  10,
  8,
  10,
  2,
  7,
  23,
  2,
  14,
  7,
  6,
  8,
  5,
  6,
  3,
  6,
  8,
  10,
  2,
  4,
  6,
  11,
  2,
  5,
  10,
  12,
  4,
  6,
  11,
  10,
  19,
  2,
  28,
  5,
  8,
  18,
  2,
  15,
  7,
  10,
  8,
  2,
  7,
  23,
  2,
  8,
  18,
  3,
  2,
  5,
  6,
  18,
  4,
  24,
  5,
  8,
  3,
  11,
  2,
  12,
  4,
  6,
  11,
  2,
  5,
  6,
  2,
  8,
  18,
  3,
  2,
  6,
  7,
  9,
  8,
  18,
  3,
  9,
  6,
  2,
  18,
  3,
  15,
  5,
  10,
  16,
  18,
  3,
  9,
  3,
  21],
 [3,
  4,
  9,
  8,
  18,
  2,
  18,
  4,
  10,
  2,
  3,
  20,
  7,
  12,
  20,
  3,
  11,
  2,
  8,
  18,
  9,
  7,
  13,
  17,
  18,
  2,
  17,
  3,
  7,
  12,
  7,
  17,
  5,
  14,
  4,
  12,
  2,
  4,
  6,
  11,
  2,
  24,
  5,
  7,
  12,
  7,
  17,
  5,
  14,
  4,
  12,
  2,
  16,
  9,
  7,
  14,
  3,
  10,
  10,
  3,
  10,
  2,
  8,
  18,
  4,
  8,
  2,
  18,
  4,
  20,
  3,
  2,
  12,
  3,
  23,
  8,
  2,
  8,
  9,
  4,
  14,
  3,
  10,
  2,
  7,
  23,
  2,
  8,
  18,
  3,
  2,
  7,
  9,
  5,
  17,
  5,
  6,
  4,
  12,
  2,
  14,
  7,
  6,
  11,
  5,
  8,
  5,
  7,
  6,
  10,
  21],
 [8,
  18,
  3,
  2,
  7,
  13,
  8,
  3,
  9,
  2,
  10,
  13,
  9,
  23,
  4,
  14,
  3,
  2,
  5,
  10,
  2,
  11,
  5,
  20,
  5,
  11,
  3,
  11,
  2,
  5,
  6,
  8,
  7,
  2,
  10,
  3,
  20,
  3,
  9,
  4,
  12,
  2,
  17,
  9,
  4,
  11,
  13,
  4,
  12,
  12,
  29,
  2,
  15,
  5,
  17,
  9,
  4,
  8,
  5,
  6,
  17,
  2,

In [16]:
max_len = 200

X = pad_sequences(
    sequences,
    maxlen=max_len,
    padding='post'
)
X

array([[  2,   6,   4, ...,   0,   0,   0],
       [138,   6,   4, ...,   0,   0,   0],
       [  8,  18,   3, ...,   0,   0,   0],
       ...,
       [232, 245, 165, ...,   0,   0,   0],
       [256, 146, 212, ...,   0,   0,   0],
       [307, 133, 132, ...,   0,   0,   0]], dtype=int32)

In [17]:
y = np.array(labels)
y

array([3, 3, 3, ..., 9, 9, 9])

In [18]:
X_train, X_test, y_train, y_test = train_test_split(
    X,
    y,
    test_size=0.2,
    random_state=42,
    stratify=y
)

In [19]:
vocab_size = len(tokenizer.word_index) + 1

In [20]:
model = Sequential()

model.add(
    Embedding(
        input_dim=vocab_size,
        output_dim=128,
        input_length=max_len
    )
)

model.add(
    Bidirectional(
        LSTM(
            128,
            dropout=0.3,
            recurrent_dropout=0.3
        )
    )
)

model.add(Dropout(0.3))

model.add(
    Dense(
        128,
        activation='relu'
    )
)

model.add(Dropout(0.3))

model.add(
    Dense(
        len(set(labels)),
        activation='softmax'
    )
)

/usr/local/lib/python3.12/dist-packages/keras/src/layers/core/embedding.py:100: UserWarning: Argument `input_length` is deprecated. Just remove it.
  warnings.warn(

In [21]:
model.compile(
    optimizer='adam',
    loss='sparse_categorical_crossentropy',
    metrics=['accuracy']
)

In [22]:
early_stop = EarlyStopping(
    monitor='val_accuracy',
    patience=3,
    restore_best_weights=True
)

In [23]:
model.fit(
    X_train,
    y_train,
    epochs=15,
    batch_size=64,
    validation_data=(X_test, y_test),
    callbacks=[early_stop]
)

Epoch 1/15
130/130 ━━━━━━━━━━━━━━━━━━━━ 187s 1s/step - accuracy: 0.3035 - loss: 2.0535 - val_accuracy: 0.4884 - val_loss: 1.4604
Epoch 2/15
130/130 ━━━━━━━━━━━━━━━━━━━━ 169s 1s/step - accuracy: 0.5207 - loss: 1.3345 - val_accuracy: 0.6214 - val_loss: 0.9917
Epoch 3/15
130/130 ━━━━━━━━━━━━━━━━━━━━ 166s 1s/step - accuracy: 0.5876 - loss: 1.0895 - val_accuracy: 0.6518 - val_loss: 0.8489
Epoch 4/15
130/130 ━━━━━━━━━━━━━━━━━━━━ 205s 1s/step - accuracy: 0.6319 - loss: 0.9437 - val_accuracy: 0.6591 - val_loss: 0.8436
Epoch 5/15
130/130 ━━━━━━━━━━━━━━━━━━━━ 198s 1s/step - accuracy: 0.6535 - loss: 0.8818 - val_accuracy: 0.7108 - val_loss: 0.7302
Epoch 6/15
130/130 ━━━━━━━━━━━━━━━━━━━━ 166s 1s/step - accuracy: 0.6649 - loss: 0.8456 - val_accuracy: 0.7403 - val_loss: 0.6864
Epoch 7/15
130/130 ━━━━━━━━━━━━━━━━━━━━ 166s 1s/step - accuracy: 0.7104 - loss: 0.7762 - val_accuracy: 0.7336 - val_loss: 0.6904
Epoch 8/15
130/130 ━━━━━━━━━━━━━━━━━━━━ 166s 1s/step - accuracy: 0.7514 - loss: 0.6605 - val_accuracy: 0.8051 - val_loss: 0.5115
Epoch 9/15
130/130 ━━━━━━━━━━━━━━━━━━━━ 199s 1s/step - accuracy: 0.7847 - loss: 0.5923 - val_accuracy: 0.8317 - val_loss: 0.4364
Epoch 10/15
130/130 ━━━━━━━━━━━━━━━━━━━━ 163s 1s/step - accuracy: 0.8063 - loss: 0.5266 - val_accuracy: 0.8395 - val_loss: 0.4273
Epoch 11/15
130/130 ━━━━━━━━━━━━━━━━━━━━ 162s 1s/step - accuracy: 0.8221 - loss: 0.4784 - val_accuracy: 0.8593 - val_loss: 0.3926
Epoch 12/15
130/130 ━━━━━━━━━━━━━━━━━━━━ 161s 1s/step - accuracy: 0.8461 - loss: 0.4216 - val_accuracy: 0.8907 - val_loss: 0.3193
Epoch 13/15
130/130 ━━━━━━━━━━━━━━━━━━━━ 161s 1s/step - accuracy: 0.8619 - loss: 0.3939 - val_accuracy: 0.8883 - val_loss: 0.3094
Epoch 14/15
130/130 ━━━━━━━━━━━━━━━━━━━━ 164s 1s/step - accuracy: 0.8637 - loss: 0.4063 - val_accuracy: 0.8941 - val_loss: 0.2865
Epoch 15/15
130/130 ━━━━━━━━━━━━━━━━━━━━ 199s 1s/step - accuracy: 0.8922 - loss: 0.3151 - val_accuracy: 0.9130 - val_loss: 0.2499

In [24]:
loss, accuracy = model.evaluate(X_test, y_test)

print("\nAccuracy :", accuracy)

65/65 ━━━━━━━━━━━━━━━━━━━━ 16s 251ms/step - accuracy: 0.9130 - loss: 0.2499

Accuracy : 0.9129593968391418

In [28]:
def detect_language(sentence):

    sentence = sentence.lower()

    seq = tokenizer.texts_to_sequences([sentence])

    seq = pad_sequences(
        seq,
        maxlen=max_len,
        padding='post'
    )

    prediction = model.predict(seq, verbose=0)

    predicted_index = np.argmax(prediction)

    confidence = np.max(prediction) * 100

    language = encoder.inverse_transform([predicted_index])

    return language[0], confidence

In [29]:
def translate_to_tamil(text):

    translated = translator.translate(
        text,
        dest='ta'
    )

    return translated.text


print("\nSupported Languages:")
print(data["Language"].unique())

Supported Languages:
['English' 'Malayalam' 'Hindi' 'Tamil' 'Portugeese' 'French' 'Dutch'
 'Spanish' 'Greek' 'Russian' 'Danish' 'Italian' 'Turkish' 'Sweedish'
 'Arabic' 'German' 'Kannada']

In [30]:
while True:

    user_text = input("\nEnter Text : ")

    if user_text.lower() == "exit":
        print("Program Ended")
        break

    # DETECT LANGUAGE
    language, confidence = detect_language(user_text)

    print("\nDetected Language :", language)

    print("Confidence:{:.2f}%".format(confidence))


    # TRANSLATE TO TAMIL
    tamil_text = translate_to_tamil(user_text)

    print("Tamil Translation :", tamil_text)

Enter Text : Je suis très heureux de vous rencontrer

Detected Language : French
Confidence:98.94%
Tamil Translation : உங்களை சந்தித்ததில் மிகவும் மகிழ்ச்சி அடைகிறேன்

Enter Text : exit
Program Ended